INSERT INTO
    PUBLIC.DIMPRODUCTS (ID, PRODUCT_ID, PRODUCT_NAME, UNIT)
SELECT
    NEXTVAL ('dimproducts_id_seq'),
    PRODUCT_ID,
    PRODUCT_NAME,
    UNIT
FROM
    PUBLIC.PRODUCTS;

INSERT INTO
    PUBLIC.DIMCUSTOMERS
SELECT
    NEXTVAL ('dimcustomers_id_seq'),
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CONTACT_NAME,
    ADDRESS,
    CITY,
    POSTAL_CODE,
    COUNTRY
FROM
    PUBLIC.CUSTOMERS;

INSERT INTO
    PUBLIC.DIMEMPLOYEES (
        ID,
        EMPLOYEE_ID,
        LAST_NAME,
        FIRST_NAME,
        BIRTH_DATE,
        PHOTO,
        NOTES
    )
SELECT
    NEXTVAL ('dimemployees_id_seg'),
    EMPLOYEE ID,
    LAST_ NAME,
    FIRST_NAME,
    BIRTH_DATE,
    PHOTO,
    NOTES
FROM
    PUBLIC.EMPLOYEES;

INSERT INTO
    PUBLIC.DIMORDERDETAILS (ID, ORDER_DETAIL_ID)
SELECT
    NEXTVAL ('dimorderdetails_id_seg'),
    ORDER_ DETAIL ID
FROM
    ORDER_DETAILS;

INSERT INTO
    PUBLIC.DIMORDERS (ID, ORDER ID)
SELECT
    NEXTVAL ('dimorders_id_seg'),
    ORDER_ID
FROM
    ORDERS;

INSERT INTO
    PUBLIC.DIMPRODUCTS (ID, PRODUCT_ID, PRODUCT_NAME, UNIT)
SELECT
    NEXTVAL ('dimproducts_id_seq'),
    PRODUCT_ID,
    PRODUCT_NAME,
    UNIT
FROM
    PUBLIC.PRODUCTS;

INSERT INTO
    PUBLIC.DIMSHIPPERS (ID, SHIPPER ID.SHIPPER_NAME, PHONE)
SELECT
    NEXTVAL ('dimshippers_id_seg'),
    SHIPPER_ ID,
    SHIPPER_NAME,
    PHONE
FROM
    PUBLIC.SHIPPERS;

INSERT INTO
    PUBLIC.DIMSUPPLIERS (
        ID,
        SUPPLIER ID,
        SUPPLIER_NAME,
        CONTACT_NAME,
        ADDRESS,
        CITY,
        POSTAL_CODE,
        COUNTRY,
        PHONE
    )
SELECT
    NEXTVAL ('dimsuppliers_id_seg'),
    SUPPLIER_ID,
    SUPPLIER_NAME,
    CONTACT_NAME,
    ADDRESS,
    CITY,
    POSTAL_CODE,
    COUNTRY.PHONE
FROM
    PUBLIC.SUPPLIERS;