INSERT INTO FACTORDERSALES
	(WITH BASE_DATA AS
			(SELECT _DATA.*
				FROM
					(WITH RAW_DATA AS
							(SELECT O. ORDER_ID,
O. CUSTOMER_ID,
O. ORDER_DATE, P. PRODUCT_ID,
P. CATEGORY_ID,
OD. QUANTITY QUANT, P. PRICE PRICE,
(OD.QUANTITY * P.PRICE) TOTAL_PRICE
								FROM ORDERS O
								JOIN ORDER_DETAILS OD ON O.ORDER_ID = OD.ORDER_ID
								JOIN PRODUCTS P ON OD.PRODUCT_ID = P. PRODUCT_ID
								JOIN CATEGORIES PC ON P. CATEGORY_ID = PC. CATEGORY_ID
								JOIN CUSTOMERS C ON O.CUSTOMER_ID = C. CUSTOMER_ID) SELECT DISTINCT RAW_DATA.ORDER_ID,
RAW_DATA. CUSTOMER_ID,
RAW_DATA. CATEGORY_ID,
RAW_DATA.ORDER_DATE, SUM (RAW_DATA. TOTAL_PRICE) OVER (PARTITION BY RAW_DATA. CATEGORY_ID,																																						RAW_DATA.CUSTOMER_ID) PRICE
						FROM RAW_DATA
						ORDER BY RAW_DATA.ORDER_ID) _DATA) SELECT NEXTVAL ('factordersales_id_seg'),
DORDER.ID,
DCUSTOMER_ID CUSTOMER_ID,
DCATEGORY.ID CATEGORY_ID,
BASE.ORDER_DATE ORDER_DATE, BASE.PRICE
		FROM DIMORDERS DORDER
		JOIN BASE_DATA BASE ON DORDER.ORDER_ID = BASE.ORDER_ID
		JOIN DIMCUSTOMERS DCUSTOMER ON DCUSTOMER.CUSTOMER_ID = BASE.CUSTOMER_ID
		JOIN DIMCATEGORIES CATEGORY ON CATEGORY.CATEGORY_ID = BASE.CATEGORY_ID);